#
# copy to ../docker-composer.specific.yml
# hhj@centrum.cz
#
version: '2'

networks:
  default:
    external:
      name: dohlestr_default

services:
    workspace_node_dev:
        environment:
          - NODE_ENV=development
#          - SERVER_BASE_URL=http://netvision-test:8089/api
#          - SERVER_BASE_URL=http://stage.b.dohlestr.dokku/api
          - SERVER_BASE_URL=http://dev.b.dohlestr/api
          - NO_SERVER_REACT=true
        networks:
          default:
            ipv4_address: 172.20.0.180

    workspace_node_prod:
        environment:
          - NODE_ENV=production
#          - SERVER_BASE_URL=http://netvision-test:8089/api
          - SERVER_BASE_URL=http://stage.b.dohlestr.dokku/api
          - NO_SERVER_REACT=true
        networks:
          default:
            ipv4_address: 172.20.0.183

    workspace_node_stage:
        extends: workspace_node_prod
        environment:
          - NODE_ENV=staging
#          - SERVER_BASE_URL=http://netvision-test:8089/api
          - SERVER_BASE_URL=http://stage.b.dohlestr.dokku/api
          - NO_SERVER_REACT=true
        networks:
          default:
            ipv4_address: 172.20.0.182

    sshd:
        networks:
          default:
            ipv4_address: 172.20.0.122
